# Generated by Django 5.0.6 on 2024-06-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarybooksdb')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarymembersdb')),
            ],
        ),
    ]
