# Generated by Django 5.0.6 on 2024-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0002_reviewdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewdb',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
