# Generated by Django 5.0.6 on 2024-06-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0003_reviewdb_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewdb',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='reviewdb',
            name='email',
        ),
    ]
