# Generated by Django 5.0.6 on 2024-07-17 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0005_rename_book_reviewdb_bookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarybooksdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarymembersdb')),
            ],
        ),
    ]
