# Generated by Django 5.0.6 on 2024-07-25 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0006_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecords',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('collected_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarybooksdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarymembersdb')),
            ],
        ),
    ]
