# Generated by Django 5.0.6 on 2024-07-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0007_bookrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sent_date', models.DateField(auto_now_add=True)),
                ('book_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.bookrecords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryAdmin.librarymembersdb')),
            ],
        ),
    ]
