# Generated by Django 5.0.6 on 2024-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryAdmin', '0008_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecords',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
